phraseapp:
  access_token: 3bb67086461ada9c0385b49a185cc8df6e3791f3243ed9dd9f4b701e6f2524d0
  project_id: 5a6d7817dd6d7626be818ec2f13262e1
  push:
    sources:
    - file: ./Mobility/Resources/<locale_code>.lproj/Localizable.strings
      params:
        update_translations: true
        tags: Localizable
        file_format: strings
        file_encoding: UTF-8
  pull:
    targets:
    - file: ./Mobility/Resources/<locale_code>.lproj/Localizable.strings
      params:
        tags: Localizable
        file_format: strings
        encoding: UTF-8
